# Generated by Django 4.2.5 on 2024-01-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ImageField(upload_to='Payment/%Y/%m/%d')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
