# Generated by Django 4.2.5 on 2024-01-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Service/Product')),
                ('duration_days', models.IntegerField(verbose_name='Day/Session')),
                ('category', models.CharField(choices=[('Training', 'Training'), ('Membership', 'Membership'), ('Tickets', 'Tickets')], max_length=20, verbose_name='Service Category')),
                ('non_refundable_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Non-refundable')),
                ('refundable_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Refundable')),
                ('basis_foundation', models.CharField(blank=True, max_length=50, null=True, verbose_name='Basis/foundation')),
                ('emi_available', models.BooleanField(default=False, verbose_name='0% EMI Available')),
                ('footfalls', models.IntegerField(blank=True, help_text='Applicable only for Tickets category', null=True)),
                ('footfalls_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
