# Generated by Django 4.2.5 on 2024-01-30 08:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_of_signature',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ImageField(default=datetime.datetime(2024, 1, 30, 8, 24, 12, 109626, tzinfo=datetime.timezone.utc), upload_to='Service/Product/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
