# Generated by Django 4.2.5 on 2024-01-31 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_service_date_of_signature_service_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ImageField(upload_to='ServicePayment/%Y/%m/%d')),
                ('category', models.CharField(max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicepayments', to='admin_app.service')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
