# Generated by Django 5.0.1 on 2024-01-22 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='Addmember/%Y/%m/%d')),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('street_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('billing_address', models.CharField(choices=[('online', 'Online'), ('case', 'Case')], max_length=20)),
                ('date_of_signature', models.DateTimeField(default=django.utils.timezone.now)),
                ('contact', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(blank=True, max_length=10, null=True)),
                ('emergency_contact2', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
