# Generated by Django 4.2.5 on 2024-01-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addmember',
            name='billing_address',
        ),
    ]
