# Generated by Django 4.2.5 on 2024-01-23 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_addmember_billing_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('images', models.ImageField(blank=True, null=True, upload_to='Document/%Y/%m/%d')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.addmember')),
            ],
        ),
    ]
