# Generated by Django 4.2.5 on 2024-01-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_registrationrequest_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='images',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='approval_images',
            field=models.ImageField(blank=True, null=True, upload_to='Document/%Y/%m/%d'),
        ),
    ]
