# Generated by Django 4.2.5 on 2024-01-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_registrationrequest_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrequest',
            old_name='approval_images',
            new_name='images',
        ),
    ]
