# Generated by Django 4.2.5 on 2024-01-23 08:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_approval_images_registrationrequest_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationrequest',
            name='images',
            field=models.ImageField(blank=True, default=datetime.datetime(2024, 1, 23, 8, 33, 13, 563448, tzinfo=datetime.timezone.utc), upload_to='Document/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
