# Generated by Django 4.2.5 on 2024-01-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
