# Generated by Django 4.2.5 on 2024-01-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer_customerapplyrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
