# Generated by Django 4.2.5 on 2024-01-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerapplyrequest',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
