# Generated by Django 4.2.5 on 2024-01-26 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_customerapplyrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rollnumber',
            field=models.CharField(default=datetime.datetime(2024, 1, 26, 6, 22, 10, 575362, tzinfo=datetime.timezone.utc), editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
