# Generated by Django 4.2.5 on 2024-01-26 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rejectedmodel_pendingmodel_pendingapprovalmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='ApprovedCustomerRequest/%Y/%m/%d')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PendingCustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='PendingCustomerRequest/%Y/%m/%d')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedCusomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='RejectedCusomerRequest/%Y/%m/%d')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='pendingmodel',
            name='member',
        ),
        migrations.RemoveField(
            model_name='rejectedmodel',
            name='member',
        ),
        migrations.DeleteModel(
            name='ApprovedModel',
        ),
        migrations.DeleteModel(
            name='PendingModel',
        ),
        migrations.DeleteModel(
            name='RejectedModel',
        ),
    ]
