# Generated by Django 4.2.5 on 2024-01-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_approvedcustomerrequest_pendingcustomerrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedCustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='RejectedCustomerRequest/%Y/%m/%d')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
        migrations.AddField(
            model_name='approvedcustomerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingapprovalmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingcustomerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerapplyrequest',
            name='images',
            field=models.ImageField(blank=True, upload_to='Customer_form/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='RejectedCusomerRequest',
        ),
    ]
