# Generated by Django 4.2.5 on 2024-01-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rejectedcustomerrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingapprovalmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingcustomerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rejectedcustomerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
