# Generated by Django 4.2.5 on 2024-01-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_pendingapprovalmodel_update_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingapprovalmodel',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='pendingcustomerrequest',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='rejectedcustomerrequest',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='pendingapprovalmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingcustomerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rejectedcustomerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
