# Generated by Django 4.2.5 on 2024-01-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_customer_customercode_alter_customer_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeDetail',
        ),
    ]
